<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    exclude-result-prefixes="sm image">

    <xsl:output method="html" encoding="UTF-8" indent="yes"/>

    <xsl:template match="/">
        <html lang="pt">
        <head>
            <meta charset="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <title>Sitemap — EDIT.</title>
            <style>
                *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
                body {
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                    font-size: 15px;
                    color: #222;
                    background: #f5f5f5;
                    padding: 40px 20px;
                }
                .wrap {
                    max-width: 960px;
                    margin: 0 auto;
                    background: #fff;
                    border-radius: 8px;
                    box-shadow: 0 1px 4px rgba(0,0,0,.12);
                    overflow: hidden;
                }
                header {
                    background: #0a0a0a;
                    color: #fff;
                    padding: 24px 32px;
                    display: flex;
                    align-items: center;
                    gap: 16px;
                }
                header h1 { font-size: 20px; font-weight: 600; }
                header p  { font-size: 13px; color: #aaa; margin-top: 4px; }
                .content  { padding: 32px; }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    font-size: 14px;
                }
                thead th {
                    text-align: left;
                    padding: 10px 12px;
                    background: #f0f0f0;
                    border-bottom: 2px solid #ddd;
                    font-weight: 600;
                    color: #555;
                    text-transform: uppercase;
                    font-size: 11px;
                    letter-spacing: .5px;
                }
                tbody tr:nth-child(even) { background: #fafafa; }
                tbody td {
                    padding: 10px 12px;
                    border-bottom: 1px solid #eee;
                    vertical-align: top;
                }
                a { color: #0060b6; text-decoration: none; word-break: break-all; }
                a:hover { text-decoration: underline; }
                .count {
                    display: inline-block;
                    background: #0a0a0a;
                    color: #fff;
                    border-radius: 12px;
                    padding: 2px 10px;
                    font-size: 12px;
                    margin-left: 8px;
                    vertical-align: middle;
                }
                h2 { font-size: 17px; margin-bottom: 16px; color: #111; }
                .meta { color: #888; font-size: 12px; }
            </style>
        </head>
        <body>
        <div class="wrap">
            <header>
                <div>
                    <h1>EDIT. — XML Sitemap</h1>
                    <p>Generated by EDIT. SEO Fix · weareedit.io</p>
                </div>
            </header>
            <div class="content">
                <xsl:apply-templates/>
            </div>
        </div>
        </body>
        </html>
    </xsl:template>

    <!-- Sitemap Index -->
    <xsl:template match="sm:sitemapindex">
        <h2>
            Sitemap Index
            <span class="count"><xsl:value-of select="count(sm:sitemap)"/> sitemaps</span>
        </h2>
        <table>
            <thead>
                <tr>
                    <th>Sitemap URL</th>
                    <th>Last Modified</th>
                </tr>
            </thead>
            <tbody>
                <xsl:for-each select="sm:sitemap">
                    <tr>
                        <td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
                        <td class="meta"><xsl:value-of select="sm:lastmod"/></td>
                    </tr>
                </xsl:for-each>
            </tbody>
        </table>
    </xsl:template>

    <!-- URL Set -->
    <xsl:template match="sm:urlset">
        <h2>
            URLs
            <span class="count"><xsl:value-of select="count(sm:url)"/> URLs</span>
        </h2>
        <table>
            <thead>
                <tr>
                    <th>URL</th>
                    <th>Last Modified</th>
                    <th>Change Freq</th>
                    <th>Priority</th>
                </tr>
            </thead>
            <tbody>
                <xsl:for-each select="sm:url">
                    <tr>
                        <td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
                        <td class="meta"><xsl:value-of select="sm:lastmod"/></td>
                        <td class="meta"><xsl:value-of select="sm:changefreq"/></td>
                        <td class="meta"><xsl:value-of select="sm:priority"/></td>
                    </tr>
                </xsl:for-each>
            </tbody>
        </table>
    </xsl:template>

</xsl:stylesheet>
