<?php
/**
 * FIX #6 & #7: XML Sitemap
 *
 * Issues fixed:
 *  - robots.txt references /sitemap_index.xml — returns 404
 *  - /sitemap.xml also returns 404
 *  - robots.txt was generated by third-party tool (smallseotools.com) — needs regenerating
 *
 * This class:
 *  - Registers /sitemap.xml and /sitemap_index.xml endpoints
 *  - Generates a proper XML sitemap with all public post types, taxonomies, and the homepage
 *  - Updates robots.txt to reference the correct sitemap URL
 */

if ( ! defined( 'ABSPATH' ) ) exit;

class EDIT_Sitemap {

    public static function init() {
        // If Rank Math is active it handles the sitemap — only keep the robots.txt fix
        // and add a filter to exclude noindex posts from Rank Math's sitemap.
        if ( defined( 'RANK_MATH_VERSION' ) ) {
            add_filter( 'robots_txt', [ __CLASS__, 'fix_robots_txt' ], 99, 2 );
            add_filter( 'rank_math/sitemap/exclude_post', [ __CLASS__, 'exclude_noindex_from_sitemap' ], 10, 2 );
            return;
        }

        self::register_endpoint();
        add_action( 'template_redirect', [ __CLASS__, 'serve_sitemap' ] );
        add_filter( 'robots_txt', [ __CLASS__, 'fix_robots_txt' ], 10, 2 );
    }

    public static function register_endpoint() {
        add_rewrite_rule( '^sitemap\.xml$', 'index.php?edit_sitemap=index', 'top' );
        add_rewrite_rule( '^sitemap_index\.xml$', 'index.php?edit_sitemap=index', 'top' );
        add_rewrite_rule( '^sitemap-([a-z_-]+)\.xml$', 'index.php?edit_sitemap=$matches[1]', 'top' );
        add_rewrite_tag( '%edit_sitemap%', '([a-z_-]+)' );
    }

    public static function serve_sitemap() {
        $type = get_query_var( 'edit_sitemap' );
        if ( ! $type ) return;

        header( 'Content-Type: application/xml; charset=UTF-8' );
        header( 'X-Robots-Tag: noindex, follow' );

        if ( $type === 'index' ) {
            echo self::generate_sitemap_index();
        } else {
            echo self::generate_sitemap( $type );
        }
        exit;
    }

    private static function generate_sitemap_index(): string {
        $settings = get_option( 'edit_seo_fix_settings', [] );
        $home_url = home_url();

        $xml  = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
        $xml .= '<?xml-stylesheet type="text/xsl" href="' . esc_url( WEAREDIT_SITE_ENGINE_URL . 'assets/sitemap.xsl' ) . '"?>' . "\n";
        $xml .= '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

        // Pages sitemap
        $xml .= self::sitemap_entry( $home_url . '/sitemap-pages.xml' );

        // Posts sitemap
        if ( post_type_exists( 'post' ) ) {
            $xml .= self::sitemap_entry( $home_url . '/sitemap-posts.xml' );
        }

        // Custom post types
        $public_cpts = get_post_types( [ 'public' => true, '_builtin' => false ], 'objects' );
        foreach ( $public_cpts as $cpt ) {
            $count = wp_count_posts( $cpt->name );
            if ( $count->publish > 0 ) {
                $xml .= self::sitemap_entry( $home_url . '/sitemap-' . $cpt->name . '.xml' );
            }
        }

        // Taxonomies sitemap
        $xml .= self::sitemap_entry( $home_url . '/sitemap-taxonomies.xml' );

        $xml .= '</sitemapindex>';
        return $xml;
    }

    private static function generate_sitemap( string $type ): string {
        $settings    = get_option( 'edit_seo_fix_settings', [] );
        $max_entries = (int) ( $settings['sitemap_entries'] ?? 1000 );

        $xml  = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
        $xml .= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"' .
                ' xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">' . "\n";

        if ( $type === 'pages' ) {
            // Homepage
            $xml .= self::url_entry( home_url( '/' ), '1.0', 'daily', date( 'c' ) );

            $pages = get_posts( [
                'post_type'      => 'page',
                'post_status'    => 'publish',
                'posts_per_page' => $max_entries,
                'no_found_rows'  => true,
            ] );
            foreach ( $pages as $page ) {
                $img = self::get_post_image( $page->ID );
                $xml .= self::url_entry(
                    get_permalink( $page->ID ),
                    '0.8',
                    'weekly',
                    get_the_modified_date( 'c', $page->ID ),
                    $img
                );
            }

        } elseif ( $type === 'posts' ) {
            $posts = get_posts( [
                'post_type'      => 'post',
                'post_status'    => 'publish',
                'posts_per_page' => $max_entries,
                'orderby'        => 'modified',
                'order'          => 'DESC',
                'no_found_rows'  => true,
            ] );
            foreach ( $posts as $post ) {
                $img = self::get_post_image( $post->ID );
                $xml .= self::url_entry(
                    get_permalink( $post->ID ),
                    '0.6',
                    'monthly',
                    get_the_modified_date( 'c', $post->ID ),
                    $img
                );
            }

        } elseif ( $type === 'taxonomies' ) {
            $taxonomies = get_taxonomies( [ 'public' => true ] );
            foreach ( $taxonomies as $taxonomy ) {
                $terms = get_terms( [
                    'taxonomy'   => $taxonomy,
                    'hide_empty' => true,
                    'number'     => $max_entries,
                ] );
                if ( is_wp_error( $terms ) ) continue;
                foreach ( $terms as $term ) {
                    $link = get_term_link( $term );
                    if ( is_wp_error( $link ) ) continue;
                    $xml .= self::url_entry( $link, '0.5', 'weekly', date( 'c' ) );
                }
            }

        } else {
            // Custom post type
            $posts = get_posts( [
                'post_type'      => sanitize_key( $type ),
                'post_status'    => 'publish',
                'posts_per_page' => $max_entries,
                'orderby'        => 'modified',
                'order'          => 'DESC',
                'no_found_rows'  => true,
            ] );
            foreach ( $posts as $post ) {
                $img = self::get_post_image( $post->ID );
                $xml .= self::url_entry(
                    get_permalink( $post->ID ),
                    '0.7',
                    'monthly',
                    get_the_modified_date( 'c', $post->ID ),
                    $img
                );
            }
        }

        $xml .= '</urlset>';
        return $xml;
    }

    private static function sitemap_entry( string $url ): string {
        return "  <sitemap>\n" .
               "    <loc>" . esc_url( $url ) . "</loc>\n" .
               "    <lastmod>" . date( 'c' ) . "</lastmod>\n" .
               "  </sitemap>\n";
    }

    private static function url_entry(
        string  $url,
        string  $priority  = '0.5',
        string  $changefreq = 'weekly',
        string  $lastmod   = '',
        ?array  $image     = null
    ): string {
        $entry  = "  <url>\n";
        $entry .= "    <loc>" . esc_url( $url ) . "</loc>\n";
        if ( $lastmod ) {
            $entry .= "    <lastmod>" . esc_html( $lastmod ) . "</lastmod>\n";
        }
        $entry .= "    <changefreq>" . esc_html( $changefreq ) . "</changefreq>\n";
        $entry .= "    <priority>" . esc_html( $priority ) . "</priority>\n";
        if ( $image ) {
            $entry .= "    <image:image>\n";
            $entry .= "      <image:loc>" . esc_url( $image['url'] ) . "</image:loc>\n";
            if ( ! empty( $image['title'] ) ) {
                $entry .= "      <image:title>" . esc_html( $image['title'] ) . "</image:title>\n";
            }
            $entry .= "    </image:image>\n";
        }
        $entry .= "  </url>\n";
        return $entry;
    }

    private static function get_post_image( int $post_id ): ?array {
        if ( ! has_post_thumbnail( $post_id ) ) return null;
        $img = wp_get_attachment_image_src( get_post_thumbnail_id( $post_id ), 'full' );
        if ( ! $img ) return null;
        return [
            'url'   => $img[0],
            'title' => get_the_title( $post_id ),
        ];
    }

    /**
     * Exclude noindex posts/pages from Rank Math's sitemap.
     * A page marked noindex should never appear in a sitemap — conflicting signals.
     */
    public static function exclude_noindex_from_sitemap( bool $exclude, \WP_Post $post ): bool {
        if ( $exclude ) return true; // already excluded by another rule

        $robots = get_post_meta( $post->ID, 'rank_math_robots', true );
        if ( is_array( $robots ) && in_array( 'noindex', $robots, true ) ) {
            return true;
        }

        return false;
    }

    /**
     * Fix robots.txt to reference the correct sitemap URL and remove smallseotools credit.
     */
    public static function fix_robots_txt( string $output, bool $public ): string {
        // Remove the smallseotools.com generator comment
        $output = preg_replace( '/^# robots\.txt generated by smallseotools\.com\s*/m', '', $output );

        // Remove any existing Sitemap: lines (we'll add the correct one)
        $output = preg_replace( '/^Sitemap:.*$/m', '', $output );

        // Remove any existing AI crawler block (prevent duplication when Rank Math also adds it)
        $output = preg_replace( '/\n*# AI Search Crawlers.*$/s', '', $output );

        // Remove duplicate blank lines
        $output = preg_replace( "/\n{3,}/", "\n\n", $output );

        // Prepend correct header and append correct sitemap
        $header  = "# robots.txt — weareedit.io\n";
        $header .= "# Updated by EDIT. SEO Fix plugin\n\n";
        $sitemap = "\nSitemap: " . home_url( '/sitemap_index.xml' ) . "\n";

        $ai_crawlers  = "\n# AI Search Crawlers\n";
        $ai_crawlers .= "User-agent: GPTBot\n";
        $ai_crawlers .= "Allow: /\n\n";
        $ai_crawlers .= "User-agent: ChatGPT-User\n";
        $ai_crawlers .= "Allow: /\n\n";
        $ai_crawlers .= "User-agent: PerplexityBot\n";
        $ai_crawlers .= "Allow: /\n\n";
        $ai_crawlers .= "User-agent: ClaudeBot\n";
        $ai_crawlers .= "Allow: /\n\n";
        $ai_crawlers .= "User-agent: anthropic-ai\n";
        $ai_crawlers .= "Allow: /\n\n";
        $ai_crawlers .= "User-agent: Google-Extended\n";
        $ai_crawlers .= "Allow: /\n\n";
        $ai_crawlers .= "User-agent: Amazonbot\n";
        $ai_crawlers .= "Allow: /\n\n";
        $ai_crawlers .= "User-agent: Applebot\n";
        $ai_crawlers .= "Allow: /\n";

        return $header . trim( $output ) . "\n" . $sitemap . $ai_crawlers;
    }
}
